services:
  uweflix:
    image: uweflix
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    
    volumes:
      - .:/app
    
    depends_on:
      - db
    
    entrypoint: ["./uweflix-entrypoint.sh"]

  db:
    
    image: postgres:latest
   
    ports:
      - "5432:5432"
    
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
    
    
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: